[package]
name = "bazuka"
version = "0.1.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde_bytes = "0.11.5"
serde_qs = "0.8"
home = "0.5.3"
db-key = "0.0.5"
ff = "0.12.0"
sha3 = "0.10.0"
bincode = "1.3.3"
rand = "0.8.5"
thiserror = "1.0"
num-bigint = "0.4"
num-integer = "0.1"
hex = "0.4.3"
zeekit = { version = "0.6.1", features = ["groth16"] }
colored = "2.0.0"
rust-randomx = "0.5.6"

# Node related deps
tokio = { version = "1", features = ["full"], optional = true }
hyper = { version = "0.14", features = ["full"], optional = true }
futures = { version = "0.3", optional = true }
leveldb = { version = "0.8.6", optional = true }
structopt = { version = "0.3", default-features = false, optional = true }
async-trait = { version = "0.1.53", optional = true }

[dev-dependencies]
tempdir = "0.3.7"

[features]
default = ["node"]
node = ["tokio", "hyper", "leveldb", "futures", "structopt", "async-trait"]
